modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

# This is the new, critical part that explicitly tells Forge where to find our Mixin config.
[[mixins]]
type = "common"
config = "advancedhostility.mixins.json"

[[mods]]
modId="advancedhostility"
version="0.0.1" # Version bump for the fix
displayName="[进阶仇恨]AdvancedHostility"
description='''A mod that overhauls mob hostility and interactions with a configurable faction and hate system.'''
displayTest="IGNORE_SERVER_VERSION"
logoFile="logo.png"

[[dependencies.advancedhostility]]
modId="forge"
mandatory=true
versionRange="[47.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.advancedhostility]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
